[package]
name = "avd-launcher-pro"
version = "1.0.0"
description = "Android Virtual Device Launcher Pro"
authors = ["Arslan10227"]
edition = "2021"

[lib]
name = "avd_launcher_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
rust-ini = "0.21.3"
which = "8.0.6"
thiserror = "2.0.20"
tokio = { version = "1.53.1", features = ["process", "macros", "rt", "sync", "io-util", "rt-multi-thread", "time"] }
dirs = "6.0.0"
base64 = "0.22.1"

[target.'cfg(windows)'.dependencies]
winreg = "0.56.0"
